version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    # volumes:
      # - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
      # - ./data:/var/lib/mysql